name: Setup Chrome and ChromeDriver

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install Google Chrome (Stable)
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+' | head -n 1)
        KNOWN_DRIVER_VERSION="117.0.5938.92"
        echo "Fallback to ChromeDriver version: $KNOWN_DRIVER_VERSION"
        wget "https://chromedriver.storage.googleapis.com/$KNOWN_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d $HOME/.local/bin/
        rm chromedriver_linux64.zip

    - name: Add ChromeDriver to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Installation
      run: |
        google-chrome --version
        chromedriver --version
