name: Update Playlist

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      uses: SeleniumHQ/setup-chromedriver@v3
      with:
        version: latest  # Pastikan serasi dengan Chrome

    - name: Check Chrome and ChromeDriver Versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python script.py

    - name: Commit and push updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Update playlist with latest stream URLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
