name: Update Playlist

on:
  schedule:
    - cron: "0 * * * *" # Jalankan setiap jam

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update playlist
      run: |
        python update_session.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Updated playlist with new session tokens"
        git push https://$GH_TOKEN@github.com/matz555/tvmsia.git main
